version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
